spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace